name: LimboBots
version: 1.0.0
main: ru.mrsteve.limbobots.LimboBots
api-version: 1.16
author: MrSteve
description: Плагин для добавления ботов (NPC-игроков) и накрутки онлайна на сервере

commands:
  limbobots:
    description: Управление ботами LimboBots
    usage: /<command> <add|remove|clear|tp|equip>
    permission: limbobots.admin
    aliases: [lb, bots]

permissions:
  limbobots.admin:
    description: Доступ к командам управления ботами LimboBots
    default: op
